apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

name: netbird-gateway

cloudProvider:
  none: {}

versions:
  kubernetes: v1.33.4

apiEndpoint: 
  host: 10.230.56.64
  port: 6443

controlPlane:
  hosts:
    - sshPort: 22040
      sshUsername: root
      publicAddress: 144.76.69.71

clusterNetwork:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  cni:
    external: {}
  kubeProxy:
    skipInstallation: true

machineController:
  deploy: false

operatingSystemManager:
  deploy: false

staticWorkers:
  hosts:

dynamicWorkers: []

helmReleases:
  - repoURL: https://helm.cilium.io/
    chart: cilium
    version: 1.17.5
    releaseName: cilium
    namespace: cilium
    wait: true
    values:
      - inline:
          operator:
            replicas: 1
          kubeProxyReplacement: "true"
          k8sServiceHost: 10.230.56.64
          k8sServicePort: 6443
