apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

name: vpn-ebillet-dk

cloudProvider:
  none: {}

versions:
  kubernetes: v1.32.0

apiEndpoint: 
  host: 46.62.135.225
  port: 6443

controlPlane:
  hosts:
    - sshPort: 22
      sshUsername: root
      sshPrivateKeyFile: ./outputs/ssh/rsa/openssh/.key
      publicAddress: 46.62.135.225

clusterNetwork:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  cni:
    external: {}
  kubeProxy:
    skipInstallation: true

machineController:
  deploy: false

operatingSystemManager:
  deploy: false

staticWorkers:
  hosts:

dynamicWorkers: []

helmReleases:
  - repoURL: https://helm.cilium.io/
    chart: cilium
    version: 1.17.5
    releaseName: cilium
    namespace: cilium
    wait: true
    values:
      - inline:
          operator:
            replicas: 1
          kubeProxyReplacement: "true"
          k8sServiceHost: 46.62.135.225
          k8sServicePort: 6443
