---
keycloakx:
  dbchecker:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
    rules:
      - host: keycloak.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: keycloak-ssl
        hosts:
          - keycloak.example.com
  extraEnv: |
    - name: KC_DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: keycloak.keycloakx-pgsql.credentials.postgresql.acid.zalan.do
          key: username
    - name: KC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak.keycloakx-pgsql.credentials.postgresql.acid.zalan.do
          key: password
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-admin
          key: KEYCLOAK_PASSWORD
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

postgresql:
  enabled: true
  access_secret: keycloakx-pgsql-postgres-pod-env
  size: 8Gi
