apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 17.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: cloudnative-pg
  namespace: argocd
spec:
  destination:
    namespace: cloudnative-pg
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/cloudnative-pg
      targetRevision: 17.0.0
      helm:
        valueFiles:
          - $values/k8s/vpn-ebillet-dk/argocd-apps/values-cloudnative-pg.yaml
    - repoURL: https://github.com/VILJkid/kubeaid-config-ebillet
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
