apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 17.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "20"
  name: keycloakx
  namespace: argocd
spec:
  destination:
    namespace: keycloakx
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/keycloakx
      targetRevision: 17.0.0
      helm:
        valueFiles:
          - $values/k8s/vpn-ebillet-dk/argocd-apps/values-keycloakx.yaml
    - repoURL: https://github.com/VILJkid/kubeaid-config-ebillet
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
