apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 17.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: netbird
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: netbird
  project: kubeaid
  sources:
    - repoURL: https://github.com/VILJkid/kubeaid-config-ebillet
      path: argocd-custom-helm-charts/netbird
      targetRevision: HEAD
      helm:
        valueFiles:
          - k8s/vpn-ebillet-dk/argocd-apps/values-netbird.yaml
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
